QiwiPay:

    Token:

    # Умножение покупки, например если заплатил 100 руб, при "Multiplication: 3", даст 100*3 = 300
    Multiplication: 1

    # Команда которая срабатывает при прохождении оплаты
    # Например /money give %player% %amount%
    # Тут встроенные плайсхолдеры - плагин PlaceholderAPI в след версиях добавлю)
    # %player% - игрок, который задонатил, %amount% - сколько задонатил
    Command: "ancapdonates:bal give %player% %amount%"

    # Перенаправляет после оплаты сюда
    Site: ""

    # Параметры требуемые для формирования оплаты
    #Телефон вводить без "8" и "+": 79987894554
    Phone: ""
    Email: ""
    # Валюта для приёма платежей
    Currency: "RUB"